---
- name: create download directory for hive
  file:
    path: "{{ hive_download_path}}"
    state: directory

- name: download hive
  get_url:
    url: "{{ hive_url }}"
    dest: "{{ hive_download_path }}/hive-{{ hive_version }}.tgz"

- name: create directory for hive
  file:
    path: "{{ hive_dir}}"
    state: directory

- name: unarchive hive
  unarchive:
    src: "{{ hive_download_path }}/hive-{{ hive_version }}.tgz"
    dest: "{{ hive_dir }}"
    creates: "hive-{{ hive_version }}"
    copy: no

- name: install MariaDB connectore
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-connector-java

- name: create mysql user
  command: mysql -e "CREATE USER '{{mysql_user}}'@'%'IDENTIFIED BY '{{ mysql_password }}';"

- name: create database
  command: mysql -e "CREATE DATABASE metastore;"

- name: give it privileges
  command: mysql -e " GRANT all on *.* to '{{ mysql_user }}'@'{{  hostvars[groups["namenode"][0]].ansible_hostname }}' identified by '{{mysql_password }}';" metastore

- name: flush privileges
  command: mysql -e "flush privileges;" metastore

- name: create schema
  command: mysql -e "SOURCE {{ hive_install_path }}/scripts/metastore/upgrade/mysql/hive-schema-2.1.0.mysql.sql;" metastore

- name: create symbolic link
  file:
    src: /usr/share/java/mysql-connector-java.jar
    dest: "{{ hive_install_path }}/lib/mysql-connector-java.jar"
    state: link

- include: start.yml
