---
- name: add HIVE_HOME env to bashrc
  lineinfile:
    dest: /root/.bashrc
    line: "export HIVE_HOME={{ hive_install_path }}"

- name: add hive binary to PATH
  lineinfile:
    dest: /root/.bashrc
    line: "export PATH=$HIVE_HOME/bin:$PATH"

- name: add jars to calsspath
  lineinfile:
    dest: /root/.bashrc
    line: "export CLASSPATH=$CLASSPATH:{{ hive_install_path }}/lib"

    #TODO(pprokop): ln -s /usr/share/java/mysql-connector-java.jar /usr/local/hive/apache-hive-2.1.1-bin/lib/

    #Create schema:
      #      SOURCE /usr/local/hive/apache-hive-2.1.1-bin/scripts/metastore/upgrade/mysql/hive-schema-2.1.0.mysql.sql;

- name: make hive conf
  template:
    src: hive-site.xml.j2
    dest: "{{ hive_install_path }}/conf/hive-site.xml"
