---
- name: create core-site.xml
  template:
    src: core-site.xml.j2
    dest: "{{  hadoop_etc_path }}/core-site.xml"

- name: create hadoop work_dir
  file:
    path: "{{ hadoop_work_dir}}"
    state: directory

- name: create hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: "{{  hadoop_etc_path }}/hdfs-site.xml"

- name: run datanode
  command: "{{ hadoop_install_path}}/sbin/hadoop-daemon.sh --config {{ hadoop_install_path }}/etc/hadoop --script {{ hadoop_install_path }}/bin/hdfs start datanode"
  when:
    - action == "start"

- name: stop datanode
  command: "{{ hadoop_install_path}}/sbin/hadoop-daemon.sh --config {{ hadoop_install_path }}/etc/hadoop --script {{ hadoop_install_path }}/bin/hdfs stop datanode"
  when:
    - action == "stop"

