- hosts: all
  gather_facts: true

- hosts: client
  roles:
  - ansible-oracle-java
  - hadoop-common
  - hadoop-client
  - yarn-client
  - spark
  - jupyter
  - hive-client
  - hbase-client
  - mapreduce
