- hosts: all
  gather_facts: true

- hosts: namenode
  vars:
    action: start
  roles:
    - hadoop-namenode
    - yarn-rm
    - mapreduce
    - mariadb
    - hive
    - hbase

- hosts: datanode
  vars:
    action: start
  roles:
    - hadoop-datanode
    - yarn-nn
    - mapreduce
