- hosts: all
  gather_facts: true

- hosts: namenode
  vars:
    action: stop
  roles:
    - hadoop-namenode
    - yarn-rm
    - mapreduce
    - mariadb
    - hbase
    - hive

- hosts: datanode
  vars:
    action: stop
  roles:
    - hadoop-datanode
    - yarn-nn
    - mapreduce
