hive_download_path: /tmp/hive
hive_dir: /usr/local/hive
hive_install_path: "{{ hive_dir }}/apache-hive-{{ hive_version }}-bin"
hive_version: 2.1.1
hive_url: "http://www-eu.apache.org/dist/hive/hive-{{ hive_version }}/apache-hive-{{ hive_version }}-bin.tar.gz"
mysql_user: hiveuser
mysql_password: password
