---
- name: install necessary packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ tensorflow_required_packages }}"

- name: install pip dependencies
  pip:
    name: "{{ item }}"
  with_items: 
    - "{{ pip_dependencies }}"
