---
- name: create download directory for hive
  file:
    path: "{{ hive_download_path}}"
    state: directory

- name: download hive
  get_url:
    url: "{{ hive_url }}"
    dest: "{{ hive_download_path }}/hive-{{ hive_version }}.tgz"

- name: create directory for hive
  file:
    path: "{{ hive_dir}}"
    state: directory

- name: unarchive hive
  unarchive:
    src: "{{ hive_download_path }}/hive-{{ hive_version }}.tgz"
    dest: "{{ hive_dir }}"
    creates: "hive-{{ hive_version }}"
    copy: no

- name: create download directory for derby
  file:
    path: "{{ derby_download_path}}"
    state: directory

- name: add HIVE_HOME env to bashrc
  lineinfile:
    dest: /root/.bashrc
    line: "export HIVE_HOME={{ hive_install_path }}"

- name: add hive binary to PATH
  lineinfile:
    dest: /root/.bashrc
    line: "export PATH=$HIVE_HOME/bin:$PATH"

- name: add jars to calsspath
  lineinfile:
    dest: /root/.bashrc
    line: "export CLASSPATH=$CLASSPATH:{{ hive_install_path }}/lib"

- name: make hive conf
  template:
    src: hive-site.xml.j2
    dest: "{{ hive_install_path }}/conf/hive-site.xml"

- name: install MariaDB connectore
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-connector-java


- name: create symbolic link
  file:
    src: /usr/share/java/mysql-connector-java.jar
    dest: "{{ hive_install_path }}/lib/mysql-connector-java.jar"
    state: link
