hadoop_namenode_hostname: big-data-1
hadoop_download_path: /tmp/hadoop
hadoop_url: "http://www.us.apache.org/dist/hadoop/common/hadoop-{{hadoop_version}}/hadoop-{{hadoop_version}}.tar.gz"
hadoop_install_path: "{{ hadoop_dir }}/hadoop-{{ hadoop_version }}"
hadoop_user: root
hadoop_version: 2.8.0
hadoop_dir: /usr/local/hadoop
hadoop_etc_path: "{{ hadoop_install_path }}/etc/hadoop"
hadoop_work_dir: /hadoop
replication_factor: 3
dfs_blocksize: 134217728 
spark_version: 2.1.1
hadoop_spark_version: 2.7
